[Settings]
UserName=Jason
UserId=c0d3c0d3-c0d3-c0d3-c0d3-c0d3c0d3c0d3
Email=jason@brody.island
Language=en-US
LogLevel=info
SaveType=0
UnlockAllDlc=true
OfflineMode=true

[DLC]
; Deluxe Bundle DLCs
12801
12802
12803