[Settings]
UserName=DedSec
UserId=auto
Email=dedsec@london.uk
Language=en-US
LogLevel=info
SaveType=0
UnlockAllDlc=true
OfflineMode=true

[DLC]
; Season Pass
330001
330002
330003

[Network]
PipeName=UPC_Demux