[Settings]
UserName=Ezio
UserId=80f33a39-e682-4d1f-b693-39267e890df2
Email=ezio@auditore.it
Language=en-US
LogLevel=info
SaveType=0
UnlockAllDlc=true
OfflineMode=true

[DLC]
; Sequence 13: Battle of Forli
; Sequence 14: Bonfire of the Vanities

[Network]
OfflineMode=true